services:
  - type: web
    name: v-hosting-bot
    env: python
    region: singapore  # or singapore for better ping
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: 6430768414
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
