services:
  - type: web
    name: telegram-bot-health
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: 6430768414
      - key: PORT
        value: 8080
  
  - type: worker
    name: telegram-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: 6430768414
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-bot-health
          property: url
